### ISSUE TITLE
mudread file missing

### ISSUE THREAD

**Issue by tungttnguyen** [diablo465/mflab_ext#1]
Hi Chenming,

I was using readHUF.m but the mudread.m is missing. Do you happen to have it? 

Thanks!

**Comment by chenmingzhang** [comment]
it is in folder read.

**Comment by tungttnguyen** [comment]
I didn't see it. Can you link me to the file? Thanks!

**Comment by coosbo** [comment]
I'm experiencing the same issue. Could I get a copy of the mudread.m as well?

**Comment by tungttnguyen** [comment]
@coosbo : if you can't get the mudread.m file, try other packages in Python or R

FloPy: https://github.com/modflowpy/flopy
RMODFLOW: https://github.com/rogiersbart/RMODFLOW
MFTools: https://github.com/dpphat/MFtools
